services:
  db: 
    image: postgres:16-alpine 
    container_name: meu-banco-pg
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fredericksen-net

  api:
    build: 
      context: .
      target: production
    container_name: minha-api-nestjs
    env_file:
    - .env
    environment:
      - FREDERICKSEN_WEB_URL=${FREDERICKSEN_WEB_URL}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fredericksen-net
  
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run --protocol http2
    depends_on:
      - api
    networks:
      - fredericksen-net

networks:
  fredericksen-net:
    driver: bridge

volumes:
  pgdata: